# Site settings
title: MingSan'
email: mingsan'email
description: > # this means to ignore newlines until "baseurl:"
  你要做我的小可爱吗?.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://mingsan.github.io" # the base hostname & protocol for your site
twitter_username: mingsan
github_username:  mingsan

# Build settings
markdown: kramdown
