# Site settings
title: MingSan'
email: mingsan'email
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://mingsan.github.io" # the base hostname & protocol for your site
twitter_username: mingsan
github_username:  mingsan

# Build settings
markdown: kramdown
